spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:3306/market
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
market:
  jwt:
    key: ${JWT_KEY}
#    access:
#      expiration: ${ACCESS_EXP}
#      header: ${ACCESS_HEAD}
#    refresh:
#      expiration: ${REFRESH_EXP}
#      header: ${REFRESH_HEAD}
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}