spring:
  data:
    redis:
      host: localhost # 수정 필요
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mysql://localhost:3306/market
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

    servlet:
      multipart:
        maxFileSize: 10MB # 파일 하나의 최대 크기
        maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

jwt:
  secret: ${JWT_KEY} # jwt key ??
  expiration: 3600000

server:
  port: 8080
  address: localhost

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}